In [18]:
import numpy as np
import os
import glob
import cv2
import helper_functions as hp
from sklearn.preprocessing import OneHotEncoder
from sklearn.utils import shuffle

In [6]:
# Load in naip data
naip_images_tif, naip_labels_tif = hp.dataset_reader('naip_2018_chips_90m_3class_classified_tiles')

reading in 30444 images


In [5]:
# Load in planetscope data
planetscope_images_tif, planetscope_labels_tif = hp.dataset_reader('planetscope_chips_90m_3class_classified_tiles')

reading in 30466 images


In [9]:
#np.unique(naip_labels_tif, axis = 0, return_counts=True)
#np.unique(planetscope_labels_tif, axis = 0, return_counts=True)

# Naip needs some data processing for the labels

(array([1, 2, 3], dtype=uint16), array([ 6236,   308, 23922], dtype=int64))

In [19]:
# Encode planetscope data
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(planetscope_labels_tif.reshape(-1, 1))
new_labels = enc.transform(planetscope_labels_tif.reshape(-1, 1)).toarray()

print(new_labels)
print(new_labels.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
(30466, 3)


In [ ]:
images_shuffle, labels_shuffle = shuffle(planetscope_image_tif, planetscope_labels_tif, random_state = 42)